"""Dedupe candidates + write a one-page bench hand-off for the top picks."""
import pandas as pd
from rdkit import Chem, DataStructs, RDLogger
from rdkit.Chem import AllChem, Descriptors, Crippen
from rdkit.Chem import FilterCatalog
from rdkit.Chem.FilterCatalog import FilterCatalogParams
RDLogger.DisableLog("rdApp.*")

prof = pd.read_csv("results/mmp1_inhibitor_candidates/candidates_profiled.csv")
prof["canon"] = prof["smiles"].map(
    lambda s: Chem.MolToSmiles(Chem.MolFromSmiles(s)) if Chem.MolFromSmiles(s) else None)
n_before = len(prof)
prof = prof.dropna(subset=["canon"]).drop_duplicates("canon").reset_index(drop=True)
print(f"deduped: {n_before} -> {len(prof)} unique structures")

cal = pd.read_csv("data/calibration/mmp1_ic50.csv")
def fp(s):
    m = Chem.MolFromSmiles(str(s))
    return AllChem.GetMorganFingerprintAsBitVect(m, 2, 2048) if m else None
known = [(r.molecule_chembl_id, fp(r.canonical_smiles), r.pIC50_median)
         for r in cal.itertuples() if fp(r.canonical_smiles)]

p = FilterCatalogParams()
p.AddCatalog(FilterCatalogParams.FilterCatalogs.BRENK)
p.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS)
cat = FilterCatalog.FilterCatalog(p)

picks = prof[prof["potent_and_MMP1_selective"]].sort_values(
    ["pIC50_mmp1", "min_MMP1_selectivity"], ascending=False)
if len(picks) < 5:
    picks = prof.sort_values(["potent_and_MMP1_selective", "pIC50_mmp1"],
                             ascending=False).head(8)

rows = []
for i, r in enumerate(picks.itertuples(), 1):
    m = Chem.MolFromSmiles(r.canon)
    f = fp(r.canon)
    s, cid, pic = max((DataStructs.TanimotoSimilarity(f, k[1]), k[0], k[2]) for k in known)
    alerts = sorted({e.GetDescription() for e in cat.GetMatches(m)})
    rows.append({
        "pick": i, "id": r.id, "smiles": r.canon,
        "MW": round(Descriptors.MolWt(m), 1), "cLogP": round(Crippen.MolLogP(m), 2),
        "pIC50_MMP1": r.pIC50_mmp1,
        "sel_vs_MMP2": r.sel_vs_mmp2, "sel_vs_MMP3": r.sel_vs_mmp3,
        "sel_vs_MMP9": r.sel_vs_mmp9, "sel_vs_MMP13": r.sel_vs_mmp13,
        "min_selectivity": r.min_MMP1_selectivity,
        "nearest_known": cid, "nearest_pIC50": pic, "nearest_Tanimoto": round(s, 2),
        "n_alerts": len(alerts), "alerts": "; ".join(alerts) or "none",
    })
out = pd.DataFrame(rows)
out.to_csv("candidates/mmp1_inhibitor/top_picks.csv", index=False)

# ---- one-page markdown ----
L = []
L.append("# Bench hand-off — top MMP-1 inhibitor candidates\n")
L.append("**Computational triage only — predictions, not measurements. Confirm in vitro.**\n")
L.append("## How these were chosen")
L.append("- Generated by BRICS recombination of 1,976 known ChEMBL MMP-1 inhibitors (novel, in applicability domain).")
L.append("- Scored by QSAR potency models for MMP-1/2/3/9/13 (held-out Spearman 0.81–0.86).")
L.append("- Kept only those predicted **potent at MMP-1 (pIC50 ≥ 7)** AND **selective over all of MMP-2/3/9/13**.")
L.append(f"- {len(prof)} unique structures after dedup; {int(prof['potent_and_MMP1_selective'].sum())} potent-and-selective.\n")
L.append("## Picks\n")
hdr = "| # | id | MW | cLogP | pred pIC50 (MMP-1) | min selectivity (log) | nearest known (Tanimoto, pIC50) | alerts |"
L.append(hdr); L.append("|" + "---|" * 8)
for r in rows:
    L.append(f"| {r['pick']} | {r['id']} | {r['MW']} | {r['cLogP']} | {r['pIC50_MMP1']} | "
             f"+{r['min_selectivity']} | {r['nearest_known']} ({r['nearest_Tanimoto']}, {r['nearest_pIC50']}) | {r['n_alerts']} |")
L.append("\n## Structures (canonical SMILES)\n")
for r in rows:
    L.append(f"- **{r['id']}**  `{r['smiles']}`")
    L.append(f"  - selectivity vs MMP-2/3/9/13 (log units): {r['sel_vs_MMP2']} / {r['sel_vs_MMP3']} / {r['sel_vs_MMP9']} / {r['sel_vs_MMP13']}")
    L.append(f"  - structural alerts: {r['alerts']}")
L.append("\n## Caveats & recommended assays")
L.append("- **Stereo-blind model**: the ECFP fingerprints ignore stereochemistry, so the QSAR cannot rank stereoisomers — the picks above collapse to **2 distinct constitutional scaffolds** (CAND-04389-type, MW 383; CAND-04423-type, MW 409), each shown as 2–3 stereoisomers with identical predictions. Stereochemistry must be resolved experimentally (or by docking).")
L.append("- **Multiple chelators / heavy alert load**: these carry a hydroxamic acid AND an N-hydroxypyridinone (both metal-binders) — strong predicted binding, but a real selectivity/tox/PK liability. This is the classic MMP-inhibitor failure chemotype; weight accordingly.")
L.append("- **Predicted potency/selectivity** (QSAR); selectivity = difference of two model predictions → errors compound. Triage prior, not truth.")
L.append("- **Synthesizability not assessed** (BRICS fragments). Most carry structural alerts (the reactive zinc-binding group + recombined fragments) — chemist review required before synthesis.")
L.append("- **Applicability**: in-domain but at the looser edge (Tanimoto ~0.5–0.6 to nearest known) → more extrapolation than close analogs.")
L.append("- **Confirm with**: (1) MMP-1 fluorogenic inhibition assay (IC50); (2) MMP-2/3/9/13 panel for the predicted selectivity; (3) standard counter-screens / cytotoxicity given the chelator chemotype.")
open("candidates/mmp1_inhibitor/BENCH_HANDOFF.md", "w").write("\n".join(L))
print("wrote candidates/mmp1_inhibitor/BENCH_HANDOFF.md + top_picks.csv")
print(f"\ntop picks: {len(rows)}")
print(out[["id", "MW", "pIC50_MMP1", "min_selectivity", "nearest_Tanimoto", "n_alerts"]].to_string(index=False))
